SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;

CREATE TABLE department (
  DeptID INT NOT NULL AUTO_INCREMENT,
  DeptName TEXT NOT NULL,
  MgrEmpID INT NOT NULL,
  Budget DECIMAL(10,0) NOT NULL,
  DeptCity TEXT NOT NULL,
  PRIMARY KEY (DeptID),
  UNIQUE KEY (MgrEmpID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE employee (
  EmpID INT NOT NULL AUTO_INCREMENT,
  EmpName TEXT NOT NULL,
  Age INT NOT NULL,
  Salary DECIMAL(10,4) NOT NULL,
  HireDate DATE NOT NULL,
  PRIMARY KEY (EmpID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE work (
  EmpID INT NOT NULL,
  DeptID INT NOT NULL,
  Percent_Time DECIMAL(10,4) NOT NULL,
  UNIQUE KEY (EmpID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

COMMIT;
